VERSION --use-function-keyword 0.7

CONFIG:
    FUNCTION
    ARG name = "Earthly CI"
    ARG email = "earthly.ci@example.com"
    RUN \
        git config --global user.name $name \
        && git config --global user.email $email

TAG:
    FUNCTION
    ARG tag = $(svu next)
    RUN git tag -am $tag $tag || echo Tag already exists: $tag

PUSH:
    FUNCTION
    ARG remote = origin
    ARG refs = main $(svu current)
    RUN --push git push --atomic $remote $refs

TAG_PUSH:
    FUNCTION
    DO +TAG
    DO +PUSH

git-base:
    FROM caarlos0/svu:v1.12.0
    DO +CONFIG

tag:
    FROM +git-base
    DO +TAG

tag-local:
    LOCALLY
    DO +TAG

push:
    FROM +git-base
    DO +PUSH

push-local:
    LOCALLY
    DO +PUSH

tag-push:
    FROM +git-base

tag-push-local:
    LOCALLY
    DO +TAG_PUSH
