VERSION 0.8

# build-all-platforms is a multiplatform build example
# NOTE May be very slow!
build-all-platforms:
    BUILD --platform=linux/amd64 --platform=linux/arm/v8 +build

build:
    FROM golang:1.21-alpine
    WORKDIR /work
    ARG name = example/myimage
    ARG tag = latest
    COPY main.go .
    RUN go build -o /go/bin/hello main.go
    ENTRYPOINT ["/go/bin/hello"]
    SAVE IMAGE --push $name:$tag

steampipe:
    FROM turbot/steampipe:0.21.3
    RUN steampipe plugin install hackernews
    COPY query.sql .
    RUN steampipe query query.sql
