VERSION 0.8

deps:
    FROM alpine:edge
    ARG version = 0.11.0-r3
    RUN apk add --no-cache zig=$version --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing/

dev:
    FROM +deps
    WORKDIR /work
    RUN apk add --no-cache bash jq tmux vim
    RUN --interactive /bin/bash
