# TODO: goreleaser, gofumpt, goimports

VERSION --use-function-keyword 0.7

SETUP:
    FUNCTION
    WORKDIR /work
    COPY . .

LINT:
    FUNCTION
    FROM golangci/golangci-lint:v1.55
    DO +SETUP
    RUN golangci-lint run --enable gofumpt,revive

release:
    FROM goreleaser/goreleaser:v1.23.0
