# TODO: goimports

VERSION 0.8

LINT:
    FUNCTION
    FROM golangci/golangci-lint:v1.55
    WORKDIR /work
    ARG linters = gofumpt,goimports,revive
    COPY . .
    RUN --secret GH_TOKEN golangci-lint run --enable $linters

deps-lint:
    FROM golangci/golangci-lint:v1.55
    SAVE ARTIFACT /usr/bin/golangci-lint

test-lint:
    FROM golang:1.21-alpine
    WORKDIR /work
    COPY +deps-lint/golangci-lint /usr/local/bin/
    ARG repo_url = https://github.com/qjcg/horeb
    GIT CLONE $repo_url .
    DO +LINT

RELEASE:
    FUNCTION
    FROM goreleaser/goreleaser:v1.23.0
    WORKDIR /work
    RUN apk add --no-cache upx

    ARG repo_url = ""
    ARG branch = main
    IF [ $repo_url != "" ]
       RUN git clone --branch $branch $repo_url .
    ELSE
       COPY . .
    END

    ARG args = --clean --snapshot --skip docker
    RUN --secret GITHUB_TOKEN=GH_TOKEN goreleaser release $args
    SAVE ARTIFACT dist

test-release:
    DO +RELEASE --repo_url https://github.com/qjcg/horeb
